# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-13 13:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarginRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExchangeId', models.CharField(default='', max_length=10)),
                ('InstrumentId', models.CharField(default='', max_length=20)),
                ('SpHeMarks', models.CharField(default='', max_length=1)),
                ('LSmarks', models.CharField(default='', max_length=1)),
                ('InvestorMarginRateByMoney', models.DecimalField(decimal_places=5, max_digits=8)),
                ('InvestorMarginRateByAmount', models.CharField(default='', max_length=1)),
                ('ExchangeMarginRateByMoney', models.DecimalField(decimal_places=5, max_digits=8)),
                ('ExchangeMarginRateByAmount', models.CharField(default='', max_length=1)),
                ('InvestorOpMarginRateByMoney', models.DecimalField(decimal_places=5, max_digits=8)),
                ('InvestorOpMarginRateByAmount', models.CharField(default='', max_length=1)),
            ],
            options={
                'verbose_name': '\u4fdd\u8bc1\u91d1\u7387',
                'verbose_name_plural': '\u4fdd\u8bc1\u91d1\u7387',
            },
        ),
        migrations.CreateModel(
            name='OpRateSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvestorId', models.CharField(default='', max_length=12)),
                ('ExchangeId', models.CharField(default='', max_length=10)),
                ('InstrumentId', models.CharField(default='', max_length=20)),
                ('SpHeMarks', models.CharField(default='', max_length=1)),
                ('OCmarks', models.CharField(default='', max_length=1)),
                ('InvestorRateByMoney', models.DecimalField(decimal_places=5, max_digits=8)),
                ('InvestorRateByAmount', models.CharField(default='', max_length=1)),
                ('ExchangeRateByMoney', models.DecimalField(decimal_places=5, max_digits=8)),
                ('ExchangeRateByAmount', models.CharField(default='', max_length=1)),
                ('insert_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '\u671f\u8d27\u624b\u7eed\u8d39\u8d39\u7387',
                'verbose_name_plural': '\u671f\u8d27\u624b\u7eed\u8d39\u8d39\u7387',
            },
        ),
        migrations.RenameModel(
            old_name='RateSetting',
            new_name='FuRateSetting',
        ),
        migrations.AlterModelOptions(
            name='furatesetting',
            options={'verbose_name': '\u671f\u8d27\u624b\u7eed\u8d39\u8d39\u7387', 'verbose_name_plural': '\u671f\u8d27\u624b\u7eed\u8d39\u8d39\u7387'},
        ),
    ]
