# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-18 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarginRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExchangeId', models.CharField(default='', max_length=10)),
                ('InstrumentId', models.CharField(default='', max_length=20)),
                ('SpHeMarks', models.CharField(default='', max_length=1)),
                ('LSmarks', models.CharField(default='', max_length=1)),
                ('InvestorMarginRateByMoney', models.DecimalField(decimal_places=5, max_digits=8)),
                ('InvestorMarginRateByAmount', models.CharField(default='', max_length=1)),
                ('ExchangeMarginRateByMoney', models.DecimalField(decimal_places=5, max_digits=8)),
                ('ExchangeMarginRateByAmount', models.CharField(default='', max_length=1)),
                ('InvestorOpMarginRateByMoney', models.DecimalField(decimal_places=5, max_digits=8)),
                ('InvestorOpMarginRateByAmount', models.CharField(default='', max_length=1)),
            ],
            options={
                'verbose_name': '\u4fdd\u8bc1\u91d1\u7387',
                'verbose_name_plural': '\u4fdd\u8bc1\u91d1\u7387',
            },
        ),
    ]
