# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-19 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CTP2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_InvestorFundDtl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACCOUNTID', models.CharField(default='', max_length=10)),
                ('SPECACTUAL', models.CharField(default='', max_length=10)),
                ('MARGIN', models.CharField(default='', max_length=10)),
                ('SPECMARGIN', models.CharField(default='', max_length=10)),
                ('nan', models.CharField(default='', max_length=10)),
                ('BOPTMARKETVALUE', models.CharField(default='', max_length=10)),
                ('SOPTMARKETVALUE', models.CharField(default='', max_length=10)),
                ('OPTSTRIKEPROFIT', models.CharField(default='', max_length=10)),
                ('SMARGIN', models.CharField(default='', max_length=10)),
                ('HMARGIN', models.CharField(default='', max_length=10)),
                ('OPTPREMIUMINCOME', models.CharField(default='', max_length=10)),
                ('DELIVMARGIN', models.CharField(default='', max_length=10)),
                ('ACTUAL', models.CharField(default='', max_length=10)),
                ('SPECFEE', models.CharField(default='', max_length=10)),
                ('EXCHMARGIN', models.CharField(default='', max_length=10)),
                ('EXCHSMARGIN', models.CharField(default='', max_length=10)),
                ('EXCHHMARGIN', models.CharField(default='', max_length=10)),
                ('EXCHDELIVMARGIN', models.CharField(default='', max_length=10)),
                ('EXCHTRANSFEE', models.CharField(default='', max_length=10)),
                ('EXCHDELIVFEE', models.CharField(default='', max_length=10)),
                ('OPTPREMIUMPAY', models.CharField(default='', max_length=10)),
                ('CLOSEPROFIT', models.CharField(default='', max_length=10)),
                ('CLOSEPROFITBYTRADE', models.CharField(default='', max_length=10)),
                ('POSITIONPROFIT', models.CharField(default='', max_length=10)),
                ('POSITIONPROFITBYTRADE', models.CharField(default='', max_length=10)),
                ('TRANSFEE', models.CharField(default='', max_length=10)),
                ('DELIVFEE', models.CharField(default='', max_length=10)),
            ],
            options={
                'verbose_name': '\u6295\u8d44\u8005\u5206\u4ea4\u6613\u6240\u8d44\u91d1',
                'verbose_name_plural': '\u6295\u8d44\u8005\u5206\u4ea4\u6613\u6240\u8d44\u91d1',
            },
        ),
    ]
