# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-19 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CTP2', '0003_t_brokerfund_t_investorclosedtl_t_investorfund_t_investortradefeedtl_t_invstinstrsettleinfo_t_invstp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marginrate',
            options={'verbose_name': '\u7ed3\u679c\u5bfc\u5165', 'verbose_name_plural': '\u7ed3\u679c\u5bfc\u5165'},
        ),
    ]
