# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-20 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CTP2', '0005_auto_20170920_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marginrate',
            name='ExchangeId',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_brokerfund',
            name='CLOSEPROFIT',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_brokerfund',
            name='DELIVFEE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_brokerfund',
            name='DEPOSIT',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_brokerfund',
            name='EXCHANGEID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_brokerfund',
            name='EXCHDELIVMARGIN',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_brokerfund',
            name='EXCHHMARGIN',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_brokerfund',
            name='EXCHMARGIN',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_brokerfund',
            name='EXCHSMARGIN',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_brokerfund',
            name='EXCHTRANSFEE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_brokerfund',
            name='FUNDIN',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_brokerfund',
            name='FUNDOUT',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_brokerfund',
            name='LASTDEPOSIT',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_brokerfund',
            name='MORTGAGE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_brokerfund',
            name='OPTPREMIUMINCOME',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_brokerfund',
            name='OPTPREMIUMPAY',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_brokerfund',
            name='OPTSTRIKEPROFIT',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_brokerfund',
            name='POSITIONPROFIT',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_brokerfund',
            name='PREPA',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_brokerfund',
            name='REMAIN',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_brokerfund',
            name='STRIKEFEE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_brokerfund',
            name='WITHDRAWQUOTA',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorclosedtl',
            name='ACCOUNTID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorclosedtl',
            name='INVESTUNITID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorclosedtl',
            name='closeprice',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorclosedtl',
            name='closeprofitbydate',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorclosedtl',
            name='closeprofitbytrade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorclosedtl',
            name='hedgeflag',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorclosedtl',
            name='instrumentid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorclosedtl',
            name='investorid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorclosedtl',
            name='lastsettlementprice',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorclosedtl',
            name='offsetflag',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorclosedtl',
            name='openprice',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorclosedtl',
            name='orgtradeid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorclosedtl',
            name='posidirection',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorclosedtl',
            name='tradeid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorclosedtl',
            name='volume',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorclosedtl',
            name='volumemultiple',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfund',
            name='ACCOUNTID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfund',
            name='CALLMARGIN',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfund',
            name='DEPOSIT',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfund',
            name='DEPOSITBYTRADE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfund',
            name='FUNDIN',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfund',
            name='FUNDMORTGAGEIN',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfund',
            name='FUNDMORTGAGEMARGIN',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfund',
            name='FUNDMORTGAGEOUT',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfund',
            name='FUNDOUT',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfund',
            name='LASTDEPOSIT',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfund',
            name='LASTDEPOSITBYTRADE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfund',
            name='LOWESTINTEREST',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfund',
            name='MARKETDEPOSIT',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfund',
            name='MORTGAGE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfund',
            name='PREPA',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfund',
            name='REMAIN',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfund',
            name='RESERVE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfund',
            name='WITHDRAWQUOTA',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfunddtl',
            name='ACCOUNTID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfunddtl',
            name='ACTUAL',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfunddtl',
            name='BOPTMARKETVALUE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfunddtl',
            name='CLOSEPROFIT',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfunddtl',
            name='CLOSEPROFITBYTRADE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfunddtl',
            name='DELIVFEE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfunddtl',
            name='DELIVMARGIN',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfunddtl',
            name='EXCHDELIVFEE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfunddtl',
            name='EXCHDELIVMARGIN',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfunddtl',
            name='EXCHHMARGIN',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfunddtl',
            name='EXCHMARGIN',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfunddtl',
            name='EXCHSMARGIN',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfunddtl',
            name='EXCHTRANSFEE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfunddtl',
            name='HMARGIN',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfunddtl',
            name='MARGIN',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfunddtl',
            name='OPTPREMIUMINCOME',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfunddtl',
            name='OPTPREMIUMPAY',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfunddtl',
            name='OPTSTRIKEPROFIT',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfunddtl',
            name='POSITIONPROFIT',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfunddtl',
            name='POSITIONPROFITBYTRADE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfunddtl',
            name='SMARGIN',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfunddtl',
            name='SOPTMARKETVALUE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfunddtl',
            name='SPECACTUAL',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfunddtl',
            name='SPECFEE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfunddtl',
            name='SPECMARGIN',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investorfunddtl',
            name='TRANSFEE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investortradefeedtl',
            name='ACCOUNTID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investortradefeedtl',
            name='INVESTUNITID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investortradefeedtl',
            name='POSIDIRECTION',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investortradefeedtl',
            name='exchtransfee',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investortradefeedtl',
            name='hedgeflag',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investortradefeedtl',
            name='instrumentid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investortradefeedtl',
            name='investorid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investortradefeedtl',
            name='offsetflag',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investortradefeedtl',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investortradefeedtl',
            name='tradeid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investortradefeedtl',
            name='transfee',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investortradefeedtl',
            name='volume',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_investortradefeedtl',
            name='volumemultiple',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='ACCOUNTID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='BAVGCOST',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='BCLOSEPROFITBYDATE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='BCLOSEPROFITBYTRADE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='BMARGIN',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='BPOSITIONPROFITBYDATE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='BPOSITIONPROFITBYTRADE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='BTOTALAMT',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='DELIVFEE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='EXCHBMARGIN',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='EXCHDELIVFEE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='EXCHPERFORMFEE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='EXCHSETTLEMENTFEE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='EXCHSMARGIN',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='EXCHSTRIKEFEE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='EXCHTRANSFEE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='INVESTUNITID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='PERFORMFEE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='SAVGCOST',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='SCLOSEPROFITBYDATE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='SCLOSEPROFITBYTRADE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='SETTLEMENTFEE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='SMARGIN',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='SPOSITIONPROFITBYDATE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='SPOSITIONPROFITBYTRADE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='STOTALAMT',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='STRIKEFEE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='TRANSFEE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='VOLUMEMULTIPLE',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='hedgeflag',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='instrumentid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstinstrsettleinfo',
            name='investorid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstpositiondtl',
            name='INVESTUNITID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstpositiondtl',
            name='MARGINRATEBYMONEY',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstpositiondtl',
            name='exchmargin',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstpositiondtl',
            name='hedgeflag',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstpositiondtl',
            name='instrumentid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstpositiondtl',
            name='investorid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstpositiondtl',
            name='lastsettlementprice',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstpositiondtl',
            name='margin',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstpositiondtl',
            name='openprice',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstpositiondtl',
            name='posidirection',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstpositiondtl',
            name='positionprofitbydate',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstpositiondtl',
            name='positionprofitbytrade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstpositiondtl',
            name='settlementprice',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstpositiondtl',
            name='tradeid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstpositiondtl',
            name='volume',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_invstpositiondtl',
            name='volumemultiple',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_trade',
            name='ACCOUNTID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_trade',
            name='INVESTUNITID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_trade',
            name='direction',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_trade',
            name='hedgeflag',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_trade',
            name='instrumentid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_trade',
            name='investorid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_trade',
            name='offsetflag',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_trade',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_trade',
            name='tradeid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_trade',
            name='volume',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='t_trade',
            name='volumemultiple',
            field=models.CharField(default='', max_length=100),
        ),
    ]
